name: circumnutation_pipeline
channels:
  - anaconda
  - conda-forge
dependencies:
  - abseil-cpp=20211102.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.8
  - aiosignal=1.3.2
  - alembic=1.16.1
  - annotated-types=0.7.0
  - antlr-python-runtime=4.13.2
  - anyio=4.9.0
  - aom=3.5.0
  - appnope=0.1.4
  - asttokens=3.0.0
  - astunparse=1.6.3
  - async-timeout=5.0.1
  - blas=2.131
  - blas-devel=3.9.0
  - blinker=1.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - cattrs=1.1.1
  - certifi=2025.4.26
  - cffi=1.17.1
  - click=8.1.8
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - coloredlogs=14.0
  - comm=0.2.2
  - contourpy=1.2.1
  - cryptography=39.0.0
  - cycler=0.12.1
  - cytoolz=1.0.1
  - dagster=1.10.19
  - dagster-pipes=1.10.19
  - dagster-shared=1.10.19
  - dask-core=2024.8.0
  - debugpy=1.8.14
  - decorator=5.2.1
  - docstring_parser=0.16
  - docutils=0.21.2
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.0
  - ffmpeg=4.4.2
  - fftw=3.3.10
  - filelock=3.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.2
  - freetype=2.12.1
  - frozenlist=1.6.0
  - fsspec=2025.5.1
  - gast=0.4.0
  - geos=3.13.1
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - giflib=5.2.2
  - glib=2.80.2
  - glib-tools=2.80.2
  - gmp=6.3.0
  - gnutls=3.7.9
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - greenlet=3.2.3
  - grpc-cpp=1.46.4
  - grpcio-health-checking=1.46.3
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - h11=0.16.0
  - h2=4.2.0
  - h5py=3.8.0
  - harfbuzz=5.3.0
  - hdf5=1.12.2
  - hpack=4.1.0
  - humanfriendly=10.0
  - hyperframe=6.1.0
  - icu=70.1
  - imagecodecs-lite=2019.12.3
  - imageio=2.37.0
  - imgaug=0.4.0
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.18.1
  - itsdangerous=2.2.0
  - jasper=2.0.33
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - jpeg=9e
  - jsmin=3.0.1
  - jsonpickle=1.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keras=2.9.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.14
  - lerc=4.0.0
  - libabseil=20211102.0
  - libaec=1.1.3
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=14.0.6
  - libcurl=7.87.0
  - libcxx=20.1.6
  - libdeflate=1.14
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libglib=2.80.2
  - libiconv=1.18
  - libidn2=2.3.8
  - libintl=0.24.1
  - libintl-devel=0.24.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.51.0
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopencv=4.6.0
  - libopus=1.5.2
  - libpng=1.6.43
  - libpq=15.1
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.10.0
  - libtasn1=4.20.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.5.0
  - libxcb=1.13
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzlib=1.2.13
  - llvm-openmp=20.1.6
  - locket=1.0.0
  - mako=1.3.10
  - marimo=0.13.15
  - markdown-it-py=3.0.0
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - multidict=6.4.4
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - narwhals=1.41.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.2
  - nspr=4.36
  - nss=3.100
  - oauthlib=3.2.2
  - openblas=0.3.29
  - opencv=4.6.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openpyxl=3.1.5
  - openssl=1.1.1w
  - opt_einsum=3.4.0
  - p11-kit=0.24.1
  - packaging=25.0
  - pandas=2.2.3
  - parso=0.8.4
  - partd=1.4.2
  - patsy=1.0.1
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=25.1.1
  - pixman=0.46.0
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - propcache=0.3.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-opencv=4.6.0
  - pycparser=2.22
  - pydantic=2.11.4
  - pydantic-core=2.33.2
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pykalman=0.9.7
  - pymdown-extensions=10.15
  - pyopenssl=23.2.0
  - pyparsing=3.2.3
  - pyside2=5.15.8
  - pysocks=1.7.1
  - python=3.9.15
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.0
  - python-flatbuffers=1.12
  - python-rapidjson=1.20
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytz=2024.1
  - pyu2f=0.1.5
  - pywavelets=1.6.0
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt-main=5.15.8
  - qtpy=2.4.3
  - re2=2022.06.01
  - readline=8.2
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - rich=14.0.0
  - rsa=4.9.1
  - ruff=0.11.13
  - scikit-image=0.19.3
  - scikit-learn=1.0
  - scikit-video=1.1.11
  - scipy=1.7.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - shapely=2.0.7
  - snappy=1.1.10
  - sniffio=1.3.1
  - sqlalchemy=2.0.41
  - sqlite=3.46.0
  - stack_data=0.6.3
  - starlette=0.47.0
  - statsmodels=0.14.1
  - structlog=25.4.0
  - svt-av1=1.4.1
  - tabulate=0.9.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.9.1
  - tensorflow-base=2.9.1
  - tensorflow-estimator=2.9.1
  - tensorflow-hub=0.12.0
  - threadpoolctl=3.6.0
  - tifffile=2020.6.3
  - tk=8.6.13
  - tomli=2.2.1
  - tomlkit=0.13.3
  - toolz=1.0.0
  - toposort=1.10
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.14.0
  - typing-inspection=0.4.1
  - typing_extensions=4.14.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - universal_pathlib=0.2.6
  - uvicorn=0.34.3
  - watchdog=5.0.3
  - wcwidth=0.2.13
  - websockets=15.0.1
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.20.0
  - zeromq=4.3.5
  - zipp=3.22.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - attrs==24.2.0
      - backoff==2.2.1
      - cachetools==5.5.0
      - charset-normalizer==3.3.2
      - dagster-graphql==1.10.19
      - dagster-webserver==1.10.19
      - efficientnet==1.0.0
      - google-auth==2.34.0
      - gql==3.5.3
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - grpcio==1.66.1
      - hdmf==3.14.3
      - httptools==0.6.4
      - idna==3.8
      - image-classifiers==1.0.0
      - imgstore==0.2.9
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - keras-applications==1.0.8
      - libclang==18.1.1
      - markdown==3.7
      - markupsafe==2.1.5
      - ndx-pose==0.1.1
      - nixio==1.5.3
      - numpy==1.24.4
      - opt-einsum==3.3.0
      - protobuf==5.29.5
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pynwb==2.8.1
      - qimage2ndarray==1.10.0
      - referencing==0.35.1
      - requests-toolbelt==1.0.0
      - rpds-py==0.20.0
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - segmentation-models==1.0.1
      - six==1.15.0
      - sleap==1.3.4
      - tensorboard==2.9.1
      - tensorflow-macos==2.9.2
      - tensorflow-metal==0.5.0
      - termcolor==2.4.0
      - tzlocal==5.2
      - urllib3==2.2.2
      - uvloop==0.21.0
      - watchfiles==1.0.5
      - werkzeug==3.0.4
      - wrapt==1.16.0
