setup:
  experiment_name: "rice-scan"
  plate_number: "002"
  treatment: "GA3"
  num_plants: 10
  overwrite_duplicate: False

path:
  raw_images: "/Users/andrewoconnor/Projects/circumnutation-pipeline/test/data"
  labels: "/Users/andrewoconnor/Projects/circumnutation-pipeline/test/test_labels.v001.slp"

model:
  centroid_sigma: 2.5
  node_sigma: 2.3
  centroid_model:
    batch_size: 1
  centered_instance_model:
    batch_size: 4
    crop: 64

predict:
  track: "flow"
  similarity: "centroid"
  frame_window: 10